Local token storage
csjoblinksreddit/Spotify-Concert-Playlist pull request #10
Opened 2020-08-09 09:26 UTC by berabulut

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines. For the guidelines check the README.
- [ ] Tests for the changes have been added (for bug fixes / features). As we discussed this is optional but encouraged.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR lets us store our encrypted access token in browser.

* **What is the current behavior?** (You can also link to an open issue here)
Currently we are hard coding our access token to make api calls to spotify.

* **What is the new behavior (if this is a feature change)?**
We don't need to hard code our access token. We can safely store our token in browser and access it when we need it.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
I recomend merging this after "36-styledNavBar" before "28-createArtistPlaylist" and "37-Iframe".

2020-08-09 17:53 UTC, csjoblinksreddit commented
Can you create a ticket for this and then put it in the title as well.

2020-08-26 17:04 UTC, csjoblinksreddit requested changes
I see that you made some changes after this review. Is this pr ready for a review?

2020-08-26 17:04 UTC, csjoblinksreddit commented on frontend/src/components/home.js
> +    /*TODO:
Does this comment have to be here anymore?

2020-08-26 17:04 UTC, csjoblinksreddit commented on frontend/src/components/home.js
> +    const params = this.getHashParams();
This is a lot of stuff. What do you think about moving all of the key code into a method of its own and then calling that method inside of componentdidmount?

2020-08-26 20:21 UTC, csjoblinksreddit reviewed
Overall great job! Just want to address some issues.

2020-08-28 17:47 UTC, berabulut commented on frontend/src/components/home.js
> +    const params = this.getHashParams();
I've tried to slice it as much as i can.

2020-08-31 23:48 UTC, csjoblinksreddit approved these changes

2020-08-31 23:48 UTC, merged